server:
  port: 8080

spring:
  application:
    name: client-api
  datasource:
    url: jdbc:h2:file:/data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: FULL

integration:
  viacep:
    url: https://viacep.com.br/ws/


